CREATE DATABASE IF NOT EXISTS pingmonitor;

CREATE TABLE IF NOT EXISTS IP_LIST(idx INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(idx), CompanyID INT, IP VARCHAR(16)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CompanyList(idx INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(idx),CompanyName VARCHAR(255)) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dataTable(idx INT NOT NULL AUTO_INCREMENT, PRIMARY KEY(idx),IP VARCHAR(16),pingTimes VARCHAR(16) datetime TIMESTAMP) ENGINE=InnoDB;

